### ISSUE TITLE
Unexpected Behavior: rateYo reset current rating when used on mobile browsers

### ISSUE THREAD

**Issue by wangshijun** [prrashi/rateYo#12]
First, many thanks for this amazing plugin, but I've got unexpected behavior when rateYo is used on mobile browsers.

Here are the steps to reproduce the bug:

* Install jquery rateYo plugin on mobile web page;
* Click(tap) the star to update current rating;
* Click(tap) anywhere else, the rating plugin is reset.

After inspecting the source code, the issue is probably caused by mouseleave event handler.

http://stackoverflow.com/questions/11381673/detecting-a-mobile-browser

@prrashi

**Comment by prrashi** [comment]
Hey! @wangshijun I need to handle touch events :) , Long pending task....

**Comment by wangshijun** [comment]
@prrashi , touch events is the ultimate sulution, but can we have a temporary fix for this?

**Comment by prrashi** [comment]
@wangshijun , Done!, Thanks for the contribution :+1:
