### ISSUE TITLE
How to change rating without trigger event 'ratingstars.set'

### ISSUE THREAD

**Issue by adinvadim** [prrashi/rateYo#14]

**Comment by prrashi** [comment]
Please tell me the problem more clearly,
Are you trying to set the rating ?
or
You don't want an event to be fired when you set the rating ? in that case event name is "rateyo.set" , i did not  understood "ratingstars.set" that you specified in the issue ?

**Comment by adinvadim** [comment]
Sorry, yes of course 'rateyo.set'.
yes, I don't want an event to be fired when I set the rating.

Now, I solved this problem by wrapping in custom event and work with it. Is it normal practice?

**Comment by prrashi** [comment]
Hey! @adinvadim , sorry for the delayed response... In general, people just do not listen for the event, instead of stopping it from getting fired :)  closing this issue.
