### ISSUE TITLE
Prevent initial page load from triggering onSet event

### ISSUE THREAD

**Issue by sachinlogiciel** [prrashi/rateYo#16]
If I have the rateyo Plugin embedded in a template which is then injected in the page, my onSet event handler will trigger with a value of 5, when rating = 5;

For my purposes, I only want onSet event to be called when the user actually clicks on the rating, not initially. Any ideas on how I can make this happen?

**Comment by prrashi** [comment]
hi @sachinlogiciel , In the latest version of the plugin, this is solved ,

you can download here:
JS - https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.1.1/jquery.rateyo.min.js
CSS - https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.1.1/jquery.rateyo.min.css
