### ISSUE TITLE
Half star with star width

### ISSUE THREAD

**Issue by psloboda** [prrashi/rateYo#20]
Combination of halfStar and starWidth is not rendering correctly. 

For example this simple usage of rateYo 

`$('#qualityRating').rateYo({
        starWidth: "25px",
        rating: 1.5,
        halfStar: true,
        ratedFill: '#21C0C0'
    });`

will render stars like this:

<img width="148" alt="screen shot 2017-01-06 at 23 57 47" src="https://cloud.githubusercontent.com/assets/14012806/21735681/f77e1182-d46b-11e6-936d-2a555c1a47e9.png">

**Comment by prrashi** [comment]
Hi @psloboda  I have tried your code myself, and it works fine, check this out https://jsfiddle.net/yh4od51v/
Please see if you are overriding any CSS
