### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by pavlito** [prrashi/rateYo#24]
![image](https://cloud.githubusercontent.com/assets/3610827/23913801/56fc6576-08e4-11e7-95b2-c7705a0c884f.png)

**Comment by prrashi** [comment]
Hey!, @pavlito this means that jQuery is not included properly.
see if you have included jQuery before the plugin is included, and also check if you are overriding jQuery global variable ($) anywhere in your code
