### ISSUE TITLE
Invalid rating calculation in rtl mode

### ISSUE THREAD

**Issue by HamedMasafi** [prrashi/rateYo#28]
when rateYo set to rtl ther rating value always shown one less. To correct that the flowing line:
https://github.com/prrashi/rateYo/blob/master/src/jquery.rateyo.js#L604
must change to that code:
```js
calculatedRating = maxValue - calculatedRating + 1;
```

**Comment by prrashi** [comment]
@HamedMasafi , i dont see any problem , Please check the screenshot attached.
![screen shot 2017-04-05 at 9 47 38 pm](https://cloud.githubusercontent.com/assets/1190354/24715607/a4aee43a-1a49-11e7-8e60-4e401b846576.png)

**Comment by HamedMasafi** [comment]
In rtl mode we usually set direction of body to rtl that you don't applied, check in this state, or tell me to send an example, that bug occurred jn my site and fixed by code patch that I said in previous post.

Update: test on mouse hover, the star under mouse is gray and lefts of it are golden.

**Comment by prrashi** [comment]
@HamedMasafi  , I am working on #26 , Thanks for raising the issue. I have set the direction of body to `rtl` and direction of plugin to `ltr` as you suggested. Please find the screen recording in the attached zip file
[rtl fix.zip](https://github.com/prrashi/rateYo/files/900108/rtl.fix.zip)
.
Also please send me the example in which you face this issue

**Comment by HamedMasafi** [comment]
@prrashi Take a look at this screen recording;
The option used is:
```
rating: 0,
rtl: true,
fullStar: true
```
The style added:
```css
body{
    direction: rtl;
}
```
Everything else is your example/index.html

[Attached screen recording](https://www.sendspace.com/file/xl24ar)

**Comment by prrashi** [comment]
Hey!, @HamedMasafi , Thanks for sending me the screencast. I did the following.

1) I downloaded the source code in zip format from the repo page
2) Installed bower components using bower install
3) Removed multi colour options for the big stars in the centre
4) add `direction: rtl` for the body and added `direction: ltr` for the `.jquery-ry-container`
4) opened the file by double clicking it.
[rtl fix.zip](https://github.com/prrashi/rateYo/files/903541/rtl.fix.zip)


It worked fine, attached the screencast. please do the following
1) Send the browser details that you are using
2) Make sure you are using the latest version
3) Send me the options that you are using.

**Comment by YaseenHajajweh** [comment]
I found an alternative solution ,
search for this code `i.rtl&&(g=e-g),parseFloat(g)`
and replace it with this :
`i.rtl&&(g=e-(g-1)),parseFloat(g)`

**Comment by aliayoubi** [comment]
i fix this error by remove all style for div element spatial display style
