### ISSUE TITLE
Issue with ppl thinking grey star is already set

### ISSUE THREAD

**Issue by KrunchMuffin** [prrashi/rateYo#36]
We are having issues where some users think the grey star is already set to 5 stars so they submit with all 0.  Without resorting to force selection, is there some way I can bring attention to it?

**Comment by KrunchMuffin** [comment]
I am going to try this and see what happens

`normalFill: "rgba(221, 221, 221, 0.5)"`

**Comment by prrashi** [comment]
Hey! @KrunchMuffin , how is it going ? 

You can try overriding the css in your css file and style the gray star to something else.
Check this pen: https://codepen.io/anon/pen/zwJqXZ
