### ISSUE TITLE
Can not center align rateYo div

### ISSUE THREAD

**Issue by taharushain** [prrashi/rateYo#37]
I am using RateYo in my Ruby on Rails application along with Materialize. When I place a center-align class of Materialize on a RateYo div it has no effects on it. Any idea how to make this work? Thanks

**Comment by prrashi** [comment]
Hey Taha,

If possible, would you please reproduce this in codepen/jsfiddle and send
me the link?

**Comment by taharushain** [comment]
@prrashi Please have look at his code pen
https://codepen.io/taharushain/pen/ZKNJVE

**Comment by prrashi** [comment]
Hey @taharushain , 
The problem was that some css is missing, please do not link css from github , Please see the following link https://codepen.io/anon/pen/gWJxyK

**Comment by taharushain** [comment]
@prrashi The initial problem was that the RateYo div not centrally aligning, which still persists.

**Comment by prrashi** [comment]
@taharushain , [Block](https://developer.mozilla.org/en/docs/Web/HTML/Block-level_elements) elements would not get center aligned if you specify `text-align:center;` , you need to use `margin-left: auto;margin-right:auto;` , see the updated pen https://codepen.io/anon/pen/gWJxyK

**Comment by taharushain** [comment]
Great! It works, thanks a lot!
