### ISSUE TITLE
Add rating in dynamic list

### ISSUE THREAD

**Issue by DipakMahapurkar** [prrashi/rateYo#39]
Hello @prrashi,
Thanks for great plugin, Can i use it on mobile device android or iOS?
How to use rating bar in dynamic list, let me explain, I have server response which contains rating key how to bind data from server rating key to html, because you used single id for that div. Please help me 

Thanks

**Comment by prrashi** [comment]
@DipakMahapurkar , you need not use the "ID" attribute, I used it just for the docs page.

**Comment by prrashi** [comment]
Im going to close this ticket for now
