### ISSUE TITLE
Needs a way to report setting during initialization.

### ISSUE THREAD

**Issue by radicalbiscuit** [prrashi/rateYo#4]
In a web app I'm building, users can rate entities on a scale of 1-5 in whole number increments. These ratings are stored per user, and when a page containing these entities is loaded, the averaged rating is provided to rateYo to give an initial value.

I've provided my rateYo instance with an `onSet` function to update the users' ratings in the database over Ajax. However, because the `onSet` callback is executed even during initialization, this averaged value is sent to the server as being the user's own rating for the entity. What's more, because the column in the database is for integers and the averaged values are usually floats, a server error is raised, resulting in a nasty red mark in the javascript console.

For now I'll be working around this by storing the state as a data attribute or class in the top-level element. I propose a built-in parameter, property, or flag somewhere so an `onSet` callback may easily determine if it is being called as a result of setting during initialization.

It should be noted that simply ignoring the first `onSet` will not be a sufficient solution as some entities are without a rating initially, and therefore the first set would take place when the user selects a rating.

**Comment by prrashi** [comment]
This is a good feature to have, I shall work on it As soon as possible....

**Comment by radicalbiscuit** [comment]
If you tell me how you'd like it to be implemented (e.g. function
parameter, rateYo instance property, rateYo instance method, etc.), I'd be
happy to take a look at it and make a pull request myself. I would have
done something like that already, but I don't feel comfortable deciding
someone else's library's API. :P

I'm currently at DjangoCon in Austin, TX and have free time at nights (for
the first time in years) which is why I've been able to work on a personal
project and encounter this fantastic plugin. Let me know if I can help.

**Comment by prrashi** [comment]
@radicalbiscuit  I am glad that you want to contribute to this plugin :)

I think its better to depreciate the current flow of calling `onSet` on initialization, and instead call a new method called 'onInit'.

After the initialization, when ever user sets the rating, we shall call `onSet` as usual, but for the first time it goes to 'onInit'.

So, we need a separate method called `onInit` and an event called `rateyo.init` which we need to fire  one time on initialization.

We shall implement it in the same way `onSet` and `onChange` are implemented, what do you think ?

**Comment by radicalbiscuit** [comment]
That sounds reasonable to me. I'll get to work on it now.
