### ISSUE TITLE
Can't change colors

### ISSUE THREAD

**Issue by 50l3r** [prrashi/rateYo#40]
I can't modify the rated and normal colors.

	$('#VisitaResultadoRating').rateYo({
		ratedFill: '#00ABE8',
		normalFill: '#f1f1f1',
		rating: 5,
		fullStar: true,
		onSet: function (rating, rateYoInstance) {
			$("input[name=VisitaResultado]").val(rating);
		}
	});

![image](https://i.gyazo.com/9b54a41ee9148827cc12c2f043e391d9.png)

I use 2.3.2 version.

**Comment by prrashi** [comment]
Hey @50l3r , its working perfectly fine for me , see this pen https://codepen.io/anon/pen/weYYaO , check it out and let me know. i'm closing the issue for now, It would be great if you try to reproduce the issue in codepen and give me the link. Thank you 👍
