### ISSUE TITLE
"bower install jquery-rateyo" is stuck

### ISSUE THREAD

**Issue by polymorpher** [prrashi/rateYo#41]
The last few lines of output:

```
, {
  "type": "input",
  "message": "Answer",
  "name": "prompt",
  "level": "prompt"
```

**Comment by polymorpher** [comment]
I looked a few more pages of output messages. It turns out to be conflicts with jquery version. rateYo depends on jquery 2 whereas my project depends on jquery 3

**Comment by prrashi** [comment]
@polymorpher , i'm not sure why bower got stuck, i think it should warn something like `Unmet Dependency`.

**Comment by polymorpher** [comment]
Just tested with jQuery 3, it seems to work fine.

**Comment by prrashi** [comment]
Closing the issue
