### ISSUE TITLE
Multiple ratings are not displayed in a single html webpage

### ISSUE THREAD

**Issue by Swati-Saluja** [prrashi/rateYo#45]
There are multiple search results in my webpage. But the stars for the rating are being displayed only for the first search result. The remaining results have no stars to give the rating. How can I display the stars after each search result in the same page?

I have created a div in the results section of the html page  :- 
                      <div id="rateYo"></div>
and written the following code in the js file :-
                      <script>$("#rateYo").rateYo({
                        starWidth: "40px"
                        });</script>
What corrections need to be done in the above codes to get the desired result?

**Comment by prrashi** [comment]
@Swati-Saluja , Please do not use id, instead you can give a class like `<div class="rate-yo"></div>` for all the rating elements , and do `$(".rate-yo").rateYo()` just like how i did in docs( rateyo.fundoocode.ninja ) .
