### ISSUE TITLE
Start countor not showing

### ISSUE THREAD

**Issue by rg2609** [prrashi/rateYo#49]
I created div tag and assign rateYo to it, it renders the star but when I hover the mouse on the start it not showing the counter of the selected start

**Comment by prrashi** [comment]
@rg2609  , The counter is not part of this plugin, if you want to see example implementation , please check this one http://rateyo.fundoocode.ninja/#option-spacing , js file - http://rateyo.fundoocode.ninja/application.js?v=2.3.1

Code block 
```
$.each(elesWithCounter, function () {

    $(this).rateYo().on("rateyo.change", function (e, data) {

      $(this).next().text(data.rating);
    });
});
```
