### ISSUE TITLE
Dymanic Rating

### ISSUE THREAD

**Issue by shashank-abacus** [prrashi/rateYo#50]
hey @prrashi,
I'm using your awesome plugin but need some help. I have  a list of questions where user can rate it differently, and a cumulative average at last of all the above selected questions. last one is to show only average rating that is readOnly:true and rest all above are clickable. So problem is I'm able to calculate the rating dynamically but unable to set it in last stars. it can only be set at once for the first time when user response to que1 but it is unable to change as per user responses more. it need to change dynamically as user responses all the questions.

**Comment by rzpamidi** [comment]
@shashank-abacus  , Sorry for the delayed reply ,
This function will be helpful in this case http://rateyo.fundoocode.ninja/#method-rating

**Comment by prrashi** [comment]
@shashank-abacus , Sorry for the delayed reply ,
This function will be helpful in this case http://rateyo.fundoocode.ninja/#method-rating
