### ISSUE TITLE
How to give a minimum value of 1, for the already rated star? 

### ISSUE THREAD

**Issue by dham-tharan** [prrashi/rateYo#52]
When am clicking outside of the 1st star the value getting 0, I don't want to be like that because it was already rated field. So however i can change rating but it shouldn't below than 1.

**Comment by prrashi** [comment]
Sorry for the delayed reply.

@dham-tharan  , you can listen to the `rateyo.change` and force set to `1 ` if its less than `1` ref: http://rateyo.fundoocode.ninja/#method-rating
