### ISSUE TITLE
stroke & stroke-width

### ISSUE THREAD

**Issue by 3D-I** [prrashi/rateYo#55]
Thanks for the great work here, to begin with. 

Any chance to add `stroke` & `stroke-width` to this awesome code?

**Comment by prrashi** [comment]
@3D-I  , Please use css to style the SVG stars

**Comment by prrashi** [comment]
@3D-I  https://codepen.io/anon/pen/vzeYRP

**Comment by 3D-I** [comment]
Appreciated. :+1:
