### ISSUE TITLE
Bower ENOTFOUND - Package rateYo not found

### ISSUE THREAD

**Issue by sinner47** [prrashi/rateYo#6]
I was searching for rating plugin that is created using SVG. And this plugin is good from the others out there.

But I'm trying to install it through bower, and I get the error mentioned above.

Fixing it will be very helpful.

Thanks in advance.

**Comment by prrashi** [comment]
Hey @sinner47  its `bower install jquery-rateyo`

**Comment by sinner47** [comment]
Thanks a lot :) That helped me out.
