### ISSUE TITLE
ID of <svg /> elements

### ISSUE THREAD

**Issue by gesior** [prrashi/rateYo#7]
All SVG elements got same 'id' attribute:
**id="Layer_1"**

Is it intentional or mistake? Please answer, when you got 5 minutes.
I want to learn more about SVG.

**Comment by prrashi** [comment]
@gesior Hey!, its not intentional actually, there is no use of having them, i have to remove it... thanks for pointing it out...
I got the star from iconmonstr.com, but forgot to remove some stuff like this...

**Comment by prrashi** [comment]
Fixed it in the source....
