### ISSUE TITLE
cjs import problem

### ISSUE THREAD

**Issue by shurinskiy** [prrashi/rateYo#73]
I am trying to import this in a node.js environment for later call in a jquery context. But simple import doesn't work. Please help!

![ffffdddeee](https://user-images.githubusercontent.com/7316438/102260053-151ff100-3f3a-11eb-886c-2ba17fb7a2ca.JPG)

![sseeeedddd](https://user-images.githubusercontent.com/7316438/102260070-1c46ff00-3f3a-11eb-9f7c-ffce5990e95e.JPG)

**Comment by prrashi** [comment]
@shurinskiy  , where is `$` defined here ? , you need to do `import $ from 'jquery'`

**Comment by shurinskiy** [comment]
$ was defined earlier, by webpack externals. This works for all imports except rateyo.
