### ISSUE TITLE
JS Error in firebug console after adding multicolor code

### ISSUE THREAD

**Issue by technofreaky** [prrashi/rateYo#8]
I get the below error in firebug console.log. after adding the code for multicolor

```javascript
TypeError: v(...).toFixed is not a function
	

...ue;g=u(g)}return g}function w(a){var c=v(a).toFixed(h.precision),e=h.maxValue;c=...
```

My Plugins options are below
```javascript
end_color : "#f1c40f"
fullStar : false
halfStar : false
maxValue : "5"
minValue : 0
normalFill : "#d3d3d3"
numStars : "5"
onChange : null
onSet : null
precision : ""
ratedFill : "#c0392b"
rating : 0
readOnly : false
spacing : "5px"
starHeight : "20px"
starWidth : "20px"
start_color : "#c0392b"
```

Firebug Log Image : http://prntscr.com/9im4ly
Plugin Settings Image : http://prntscr.com/9im4ok

**Comment by prrashi** [comment]
Hi @technofreaky ,

The error is not at all related to multi-color rating. In fact, multi-color rating is not yet a part of the plugin.

Please provide integer values for the options when needed like precision, numStars, and maxValue should be integers. Right now you are providing strings, that is the cause of error i guess.

If you need to achieve multi-color rating, you need to do as it is done in the docs.
1. Include this file http://rateyo.fundoocode.ninja/bower_components/jquery-rateyo/examples/color.js
2. Implement the `getColor` similar to the one in http://rateyo.fundoocode.ninja/application.js
3. listen for `rateyo.change` and `rateyo.set` and get the color  and set the color dynamically to the plugin.

### I shall make multi-color rating a part of the plugin soon, till then please follow the steps given above.

**Comment by technofreaky** [comment]
@Prrashi

Thanks

And here are the int values

numStar : 5
minvalue : 0
maxvalue : 5
